SELECT
  INS.ANIMAL_ID,
  INS.ANIMAL_TYPE,
  INS.NAME
FROM
  ANIMAL_OUTS AS OUTS
  INNER JOIN ANIMAL_INS AS INS ON INS.ANIMAL_ID=OUTS.ANIMAL_ID
WHERE
  OUTS.SEX_UPON_OUTCOME REGEXP '^Spayed|^Neutered'
  AND INS.SEX_UPON_INTAKE REGEXP '^Intact'
ORDER BY
  INS.ANIMAL_ID;