WITH u2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
total AS (
    SELECT COUNT(*) AS total_users
    FROM u2021
)

SELECT
    YEAR(S.SALES_DATE)  AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / T.total_users, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE S
JOIN u2021 U
ON S.USER_ID = U.USER_ID
CROSS JOIN total T
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC